let mapleader = "," 
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
let &t_Co=256
syntax enable
colorscheme railscasts
set hlsearch
set cursorline cursorcolumn
set background=dark
set tabstop=2
set shiftwidth=2
set expandtab
set fdm=indent
set nowrap
set ai
call pathogen#infect()
filetype plugin indent on
set mouse=a

let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|bower_components\'

hi! link CursorColumn CursorLine

imap kj <Esc>
imap jk <Esc>

"nnoremap <C-h> <C-w>h
"nnoremap <C-k> <C-w>k
"nnoremap <C-l> <C-w>l
nnoremap <C-w>m :vnew<Enter>
nnoremap <leader>e v%:Eval<Enter>

set clipboard+=unnamed

let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_force_overwrite_completefunc = 1
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.class

map <F5> :!rake device<CR>
