brew install cmake
brew install autoconf
brew install nginx
brew install openssl
brew install python
brew install redis
brew install wget
brew install vim
brew install emacs
brew install tmux
brew install mysql
brew install postgresql
brew install sqlite
brew install node
brew install ack
brew install ctags
brew install git
brew install leiningen
brew install drip
brew install scala
brew install sbt
brew install reattach-to-user-namespace
brew install heroku-toolbelt
brew install rbenv
brew install rbenv-vars
brew install ruby-build
